export type {
  Accessibility,
  ActivityReference,
  Asset,
  AudienceLevel,
  Campaign,
  CapabilityRequirement,
  Condition,
  CoursePack,
  Effect,
  EndingNode,
  ExperienceGraph,
  ExperienceNode,
  ExperienceReference,
  Feedback,
  Goal,
  JsonPrimitive,
  Presentation,
  ReviewItem,
  SceneNode,
  SemVer,
  Skill,
  StateDeclaration,
  StateMigration,
  StatePath,
  StateSchema,
  Termination,
  Transitions,
} from './types';

export {
  SceneRunner,
  evaluateCondition,
  evaluateGoal,
  planSceneAdvance,
  selectTransition,
} from './runtime';

export {
  evaluateExperimentInfer,
  EXPERIMENT_INFER_AUTHORING_METADATA,
  type ExperimentInferEvaluation,
  type ExperimentInferState,
  type ExperimentInferTemplate,
  type ExperimentTrial,
} from './templates/experiment-infer';

export {
  DEFAULT_SENSORY_PREFERENCES,
  SENSORY_PREFERENCES_STORAGE_KEY,
  celebrateMasteryTransitions,
  loadSensoryPreferences,
  permitsCelebrationMotion,
  planMasteryCelebrations,
  playCelebrationHaptic,
  playCelebrationSound,
  saveSensoryPreferences,
  useSensoryPreferences,
  type MasteryCelebration,
  type MotionPreference,
  type SensoryPreferences,
} from './sensory';

export {
  CampaignMap,
  LegacyCourseList,
  buildCampaignMap,
  type CampaignEpisodeMap,
  type CampaignEpisodeState,
  type CampaignMapCampaign,
  type CampaignMapInput,
  type CampaignMapModel,
  type CampaignMapProps,
  type CapabilityMapItem,
  type CapabilityState,
  type LegacyCourseListProps,
} from './campaign';

export {
  DELAYED_OUTCOME_MIN_MS,
  DIAGNOSTICS_MAX_EVENTS,
  DIAGNOSTICS_MAX_EVIDENCE,
  DIAGNOSTICS_MAX_RUNS,
  DiagnosticsDashboard,
  PLAYTEST_EXPORT_FIELDS,
  PLAYTEST_EXPORT_MAX_BYTES,
  PLAYTEST_EXPORT_SCHEMA_VERSION,
  TesterDiagnosticsPanel,
  buildDiagnostics,
  compareDiagnostics,
  createPlaytestExport,
  downloadPlaytestExport,
  parsePlaytestExport,
  type CountById,
  type DiagnosticsComparison,
  type DiagnosticsComparisonRow,
  type DiagnosticsSessionInput,
  type DiagnosticsSummary,
  type DiagnosticSource,
  type PlaytestExport,
  type PlaytestExportField,
  type TesterExportConsent,
  type TesterDiagnosticsPanelProps,
} from './diagnostics';

export {
  MissionCapabilities,
  MissionCheckpointPanel,
  MissionObjectivePanel,
  MissionOutcomeBanner,
  WorldMeterPanel,
  deriveCapabilities,
  deriveObjectiveStages,
  deriveWorldMeters,
  MISSION_KIT_FIXTURES,
} from './mission';
export type {
  DerivedMissionCapability,
  DerivedMissionObjectiveStage,
  DerivedWorldMeter,
  MissionCapability,
  MissionCheckpoint,
  MissionObjective,
  MissionObjectiveStage,
  MissionObjectiveStatus,
  MissionRunState,
  MissionKitFixture,
  WorldMeter,
} from './mission';

export { describeMissionEffects, planCheckpointReplayEffects } from './effects';
export type { MissionEffectAnnouncement, MissionEffectPlan } from './effects';

export {
  aggregateMastery,
  buildSkillGraph,
  classifyLegacyQuizAttempt,
  classifyLegacyReviewState,
  MASTERY_EVIDENCE_SCHEMA_VERSION,
  normaliseExperienceEvidence,
  validateSkillGraph,
  type Confidence as EvidenceConfidence,
  type EvidenceContentVersion,
  type EvidenceContext,
  type EvidenceSource,
  type HintUse,
  type LatencyBand,
  type LegacyEvidenceRecord,
  type LegacyQuizAttempt,
  type LegacyReviewState,
  type MasteryAggregation,
  type MasteryEvidence,
  type MasteryOutcome,
  type OpportunityKind,
  type SkillEvidenceBreakdown,
  type SkillGraph,
  type SkillGraphDiagnostic,
  type SkillMasterySummary,
  type SupportLevel,
  type TransferContext,
} from './mastery';

export {
  buildLocalRecommendationPlan,
  chooseScaffolding,
  evaluateDelayedScaffolding,
  loadRecommendationLog,
  logLocalRecommendationPlan,
  RECOMMENDATION_DELAYED_EVALUATION_MS,
  RECOMMENDATION_LOG_MAX_ENTRIES,
  RECOMMENDATION_LOG_STORAGE_KEY,
  rollbackRecommendation,
} from './recommendations';
export type {
  LocalRecommendationInput,
  LocalRecommendationPlan,
  RecommendationAction,
  RecommendationKind,
  RecommendationLogEntry,
  RecommendationModuleState,
  ScaffoldLevel,
  ScaffoldingEvaluation,
  ScaffoldingExposure,
  ScaffoldingRecommendation,
} from './recommendations';

export {
  EnvironmentalStatus,
  SceneActivity,
  SceneBriefing,
  SceneCaption,
  SceneConsequence,
  SceneDebrief,
  SceneDialogue,
  SceneError,
  SceneObjective,
  SceneShell,
  SceneTransition,
} from './presentation';
export type {
  EnvironmentalStatusItem,
  EnvironmentalStatusProps,
  SceneActivityProps,
  SceneBriefingProps,
  SceneCaptionProps,
  SceneConsequenceProps,
  SceneDebriefProps,
  SceneDialogueProps,
  SceneErrorProps,
  SceneObjectiveProps,
  SceneShellProps,
  SceneTransitionProps,
} from './presentation';

export {
  loadResumePlan,
  planResume,
  type ResumeFallback,
  type ResumePlan,
  type ResumeTarget,
} from './resume';
export {
  adaptScreenSequence,
  LegacyMarkdownExperience,
  V1ScreenActivityAdapter,
  v1ScreenActivityPlugin,
  type AdaptScreenSequenceOptions,
  type LegacyMarkdownExperienceProps,
  type V1ScreenActivityAdapterProps,
  type V1ScreenActivityProps,
} from './adapters';
export type {
  ActivityOutcome,
  EvaluationContext,
  MasteryBand,
  SceneActivityRenderProps,
  SceneAdvancePlan,
  SceneRunnerPersistence,
  SceneRunnerProps,
  TraversalContext,
} from './runtime';
